---

- name: Update APT package cache
  action: apt update_cache=yes

- name: Download java_version 1.7.0
  get_url:
     url: https://javapackage12.s3.ap-south-1.amazonaws.com/jdk-7u80-linux-x64.tar.gz
     dest: /home/ubuntu

- name: Extract jdk.tar.gz into /usr/bin
  unarchive:
    src: /home/ubuntu/jdk-7u80-linux-x64.tar.gz
    dest: /usr/bin
- name: Set JAVA_HOME
  lineinfile:
    dest: /root/.bashrc
    state: present
    regexp: '^JAVA_HOME'
    line: 'export PATH=$PATH:/usr/bin/jdk1.7.0_80/bin'



