---

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes

- name: Install the MySQL packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
     - mysql-server-5.7
     - mysql-client-5.7
     - python-mysqldb
     - libmysqlclient-dev

- name: Start the MySQL service
  action: service name=mysql state=started

